--- #YAML:1.0
name:                CPAN-Test-Dummy-Perl5-Make-UnsatPrereq
version:             1.00
abstract:            CPAN Test Dummy for CPAN.pm
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    CPAN::Test::Dummy::Perl5::Make: 99999999.99
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
